/*
 *
 */

package GUI;

import java.awt.Frame;
import javax.swing.table.DefaultTableModel;

/**
 * Form secundari, classificació dels jugadors-presoners (No executar).
 * @since 2.0
 * @author Ramses - RLL862
 */
public class Classificacio_GUI extends javax.swing.JDialog {

    /**
     * Creació Form Classificacio_GUI
     * @param parent
     * @param modal
     */
    public Classificacio_GUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initParametres();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_classificacio = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_classificacio = new javax.swing.JTable();
        jButton_jugarN = new javax.swing.JButton();
        jButton_sortir = new javax.swing.JButton();
        jLabel_posicio = new javax.swing.JLabel();
        jLabel_msg = new javax.swing.JLabel();
        jLabel_punts = new javax.swing.JLabel();

        setTitle("Classificació - Dilema del presoner iterat");
        setFocusable(false);
        setModal(true);
        setName("dialogClassificacio"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        jPanel_classificacio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_classificacio.setFocusable(false);

        jTable_classificacio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Posició", "Presoner", "Puntuació", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_classificacio);
        if (jTable_classificacio.getColumnModel().getColumnCount() > 0) {
            jTable_classificacio.getColumnModel().getColumn(0).setResizable(false);
            jTable_classificacio.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTable_classificacio.getColumnModel().getColumn(1).setResizable(false);
            jTable_classificacio.getColumnModel().getColumn(2).setResizable(false);
            jTable_classificacio.getColumnModel().getColumn(3).setResizable(false);
        }

        jButton_jugarN.setText("Jugar (Nou usuari)");
        jButton_jugarN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_jugarNActionPerformed(evt);
            }
        });

        jButton_sortir.setText("Sortir del Joc");
        jButton_sortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sortirActionPerformed(evt);
            }
        });

        jLabel_posicio.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel_posicio.setText("Posició Final");

        jLabel_msg.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel_msg.setText("missatge");

        jLabel_punts.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel_punts.setText("Punts");

        javax.swing.GroupLayout jPanel_classificacioLayout = new javax.swing.GroupLayout(jPanel_classificacio);
        jPanel_classificacio.setLayout(jPanel_classificacioLayout);
        jPanel_classificacioLayout.setHorizontalGroup(
            jPanel_classificacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_classificacioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_classificacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_jugarN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_sortir, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(jLabel_msg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_punts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_posicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel_classificacioLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton_jugarN, jButton_sortir});

        jPanel_classificacioLayout.setVerticalGroup(
            jPanel_classificacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_classificacioLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel_classificacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_classificacioLayout.createSequentialGroup()
                        .addComponent(jButton_jugarN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_sortir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_msg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_posicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_punts)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel_classificacioLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_classificacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_classificacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_jugarNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_jugarNActionPerformed
        Frame[] f;
        f = GUI_DPI.getFrames();
        for (int i = 0; i < f.length; i++) {
            f[i].dispose();
        }    
        GUI_DPI mainJoc = new GUI_DPI();
        mainJoc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_jugarNActionPerformed

    private void jButton_sortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sortirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_sortirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Classificacio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Classificacio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Classificacio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Classificacio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Classificacio_GUI dialog = new Classificacio_GUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_jugarN;
    private javax.swing.JButton jButton_sortir;
    private javax.swing.JLabel jLabel_msg;
    private javax.swing.JLabel jLabel_posicio;
    private javax.swing.JLabel jLabel_punts;
    private javax.swing.JPanel jPanel_classificacio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_classificacio;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel table_classificacio;
    private final String arxiu_classificacio = "classificacio.data";
    
    /**
     * Mètode per iniciar els elements bàsics.
     */
    private void initParametres() {
        setLocationRelativeTo(null);
        table_classificacio = (DefaultTableModel) jTable_classificacio.getModel();
        Classificacio.obtenirPresoner(arxiu_classificacio);
        Classificacio.rankingAll(table_classificacio);
    }
    
    /**
     * Mètode per mostrar el resultat del jugador en el principals Labels i Jtable.
     * @param p Nom del jugador 
     */
    public void presonerResultat(String p) {     
        String presoner;
        String punts;
        boolean trobat = false;
        int posicio = 0;     
        for (int i = 0; i < table_classificacio.getRowCount() && !trobat; i++) {          
            presoner = table_classificacio.getValueAt(i,1).toString();
            if (p.equals(presoner)) {
                trobat = true;
                posicio = i;
            }
        }
        if (trobat) {
            posicio++;
        }
        jLabel_msg.setText("Enhorabona "+p.toString()+"!");
        jLabel_posicio.setText("Posició final: #" + posicio);
        jLabel_punts.setText("Punts: "+ table_classificacio.getValueAt((posicio-1),2).toString());
        jTable_classificacio.changeSelection((posicio-1), 0, false, false);
    }
    
    
    
}
