/*
 *
 */
package GUI;

import Prisoner.Prisoner;
import Prisoner.Prisoner.Action;
import Prisoner.PrisonerRandom;
import Prisoner.PrisonerTitForTat;
import Prisoner.PrisonerAltruista;
import Prisoner.PrisonerRLL862;
import Prisoner.PrisonerTraidor;
import java.awt.Color;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Form principal (Execució principal).
 * @since 2.0
 * @author Ramses - RLL862
 */
public class GUI_DPI extends javax.swing.JFrame {

    /**
     * Creates new form GUI_DPI
     */
    public GUI_DPI() {
        initComponents();
        obtenirParametres(arxiu_parametres);
        initParametres();
        getImagePresoners(); // Obtenim imatge presoners
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        JPanel_main = new javax.swing.JPanel();
        jLabel_imgPrisoner_p2 = new javax.swing.JLabel();
        jTextField_namePrisoner = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_iteracions = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_cooperacio = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel_traicio = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel_punts_p1 = new javax.swing.JLabel();
        jLabel_puntsP2 = new javax.swing.JLabel();
        jLabel_punts_p2 = new javax.swing.JLabel();
        jLabel_puntsP1 = new javax.swing.JLabel();
        jTextLabel_decisionOpp = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_historial = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButtonp2_cooperate = new javax.swing.JButton();
        jButtonp2_betray = new javax.swing.JButton();
        ini_game = new javax.swing.JButton();
        jTextField_namePlayer = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_top = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_exit = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dilema del Presoner Iterat");
        setResizable(false);

        JPanel_main.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel_imgPrisoner_p2.setText("Imatge Presoner 1");
        jLabel_imgPrisoner_p2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextField_namePrisoner.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jTextField_namePrisoner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTextField_namePrisoner.setText("Carga Presoner 1");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setLayout(new java.awt.GridLayout(3, 2));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Iteracions:");
        jPanel4.add(jLabel1);

        jLabel_iteracions.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel_iteracions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_iteracions.setText("it");
        jPanel4.add(jLabel_iteracions);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("Cooperació:");
        jPanel4.add(jLabel2);

        jLabel_cooperacio.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel_cooperacio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_cooperacio.setText("co");
        jPanel4.add(jLabel_cooperacio);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setText("Traïció:");
        jPanel4.add(jLabel6);

        jLabel_traicio.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel_traicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_traicio.setText("tr");
        jPanel4.add(jLabel_traicio);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setLayout(new java.awt.GridLayout(2, 2));

        jLabel_punts_p1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel_punts_p1.setText("Carga Presoner 1");
        jPanel5.add(jLabel_punts_p1);

        jLabel_puntsP2.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel_puntsP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_puntsP2.setText("p2");
        jPanel5.add(jLabel_puntsP2);

        jLabel_punts_p2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel_punts_p2.setText("[Nom Presoner]");
        jPanel5.add(jLabel_punts_p2);

        jLabel_puntsP1.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel_puntsP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_puntsP1.setText("p1");
        jPanel5.add(jLabel_puntsP1);

        jTextLabel_decisionOpp.setFont(new java.awt.Font("Courier 10 Pitch", 1, 24)); // NOI18N
        jTextLabel_decisionOpp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Historial", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 10))); // NOI18N
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jTable_historial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Iteració", "Presoner 1", "Presoner 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_historial.setEnabled(false);
        jTable_historial.setFocusable(false);
        jScrollPane1.setViewportView(jTable_historial);
        if (jTable_historial.getColumnModel().getColumnCount() > 0) {
            jTable_historial.getColumnModel().getColumn(0).setResizable(false);
            jTable_historial.getColumnModel().getColumn(1).setResizable(false);
            jTable_historial.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel6.add(jScrollPane1);

        javax.swing.GroupLayout JPanel_mainLayout = new javax.swing.GroupLayout(JPanel_main);
        JPanel_main.setLayout(JPanel_mainLayout);
        JPanel_mainLayout.setHorizontalGroup(
            JPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel_mainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPanel_mainLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel_imgPrisoner_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_namePrisoner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextLabel_decisionOpp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPanel_mainLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)))
                .addContainerGap())
        );
        JPanel_mainLayout.setVerticalGroup(
            JPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_mainLayout.createSequentialGroup()
                .addGroup(JPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel_mainLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jTextField_namePrisoner, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextLabel_decisionOpp, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanel_mainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_imgPrisoner_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(JPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nom Presoner:");

        jButtonp2_cooperate.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButtonp2_cooperate.setForeground(new java.awt.Color(102, 204, 0));
        jButtonp2_cooperate.setText("Cooperate");
        jButtonp2_cooperate.setEnabled(false);
        jButtonp2_cooperate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonp2_cooperateActionPerformed(evt);
            }
        });

        jButtonp2_betray.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButtonp2_betray.setForeground(new java.awt.Color(255, 0, 0));
        jButtonp2_betray.setText("Betray");
        jButtonp2_betray.setEnabled(false);
        jButtonp2_betray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonp2_betrayActionPerformed(evt);
            }
        });

        ini_game.setText("Jugar");
        ini_game.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ini_gameActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TOP 5 - Presoners", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 10))); // NOI18N
        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        jTable_top.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "P", "Presoner", "Puntuació"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_top.setEnabled(false);
        jTable_top.setFocusable(false);
        jScrollPane2.setViewportView(jTable_top);
        if (jTable_top.getColumnModel().getColumnCount() > 0) {
            jTable_top.getColumnModel().getColumn(0).setResizable(false);
            jTable_top.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTable_top.getColumnModel().getColumn(1).setResizable(false);
            jTable_top.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel7.add(jScrollPane2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_namePlayer)
                    .addComponent(ini_game, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonp2_cooperate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonp2_betray, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_namePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ini_game, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonp2_cooperate, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonp2_betray, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("Arxiu");

        jMenuItem_exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_exit.setText("Sortir");
        jMenuItem_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_exitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_exit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JPanel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem_exitActionPerformed

    private void ini_gameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ini_gameActionPerformed
        iniGame();
    }//GEN-LAST:event_ini_gameActionPerformed

    private void jButtonp2_betrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonp2_betrayActionPerformed
        accionsBetray();
    }//GEN-LAST:event_jButtonp2_betrayActionPerformed

    private void jButtonp2_cooperateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonp2_cooperateActionPerformed
        accionsCooperate();
    }//GEN-LAST:event_jButtonp2_cooperateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_DPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_DPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_DPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_DPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_DPI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel_main;
    private javax.swing.JButton ini_game;
    private javax.swing.JButton jButtonp2_betray;
    private javax.swing.JButton jButtonp2_cooperate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_cooperacio;
    private javax.swing.JLabel jLabel_imgPrisoner_p2;
    private javax.swing.JLabel jLabel_iteracions;
    private javax.swing.JLabel jLabel_puntsP1;
    private javax.swing.JLabel jLabel_puntsP2;
    private javax.swing.JLabel jLabel_punts_p1;
    private javax.swing.JLabel jLabel_punts_p2;
    private javax.swing.JLabel jLabel_traicio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_exit;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_historial;
    private javax.swing.JTable jTable_top;
    private javax.swing.JTextField jTextField_namePlayer;
    private javax.swing.JLabel jTextField_namePrisoner;
    private javax.swing.JLabel jTextLabel_decisionOpp;
    // End of variables declaration//GEN-END:variables

    /**
     * Paràmetres Joc.
     */
    // Presoner Principal
    PrisonerRLL862 p1 = new PrisonerRLL862("RLL862", "img/rll862.dat");
    // Arxiu amb paràmetres i classificació.
    private final String arxiu_parametres = "parametres.txt";
    private final String arxiu_classificacio = "classificacio.data";
    // Punts del presoners-jugadors.
    private int punts_p1 = 0;
    private int punts_p2 = 0;
    // Paràmetres.
    private final int[] parametres = new int[3];
    private int iteracions;
    private int cooperacio;
    private int traicio;
    // Imatges presoners-jugadors.
    private ImageIcon img_presoner_p2 = new ImageIcon(p1.getPrisonerImage());
    // tables.
    private DefaultTableModel table_model;
    private DefaultTableModel table_model_top;
    private String[] decisions;
    
    /**
     * Mètode per iniciar els elements bàsics.
     */
    private void initParametres() {
        setLocationRelativeTo(null);
        jTextField_namePrisoner.setText(p1.getPrisonerName());
        jLabel_punts_p1.setText(p1.getPrisonerName() + ":");
        jLabel_iteracions.setText(String.valueOf(this.iteracions));
        jLabel_cooperacio.setText(String.valueOf(this.cooperacio));
        jLabel_traicio.setText(String.valueOf(this.traicio));
        jLabel_puntsP1.setText(String.valueOf(this.punts_p1));
        jLabel_puntsP2.setText(String.valueOf(this.punts_p2));
        table_model = (DefaultTableModel) jTable_historial.getModel();
        table_model_top = (DefaultTableModel) jTable_top.getModel();
        decisions = new String[3];
        jTable_historial.getColumn("Presoner 1").setHeaderValue(p1.getPrisonerName());
        jTable_historial.getColumn("Presoner 2").setHeaderValue("Jo");
        // if per coneixer si el arxiu no té dades.
        if (!Classificacio.es_buit(arxiu_classificacio)) {
            Classificacio.obtenirPresoner(arxiu_classificacio);
            Classificacio.rankingTOP(table_model_top);
        }
    }

    /**
     * Mètode per iniciar el joc.
     */
    private void iniGame() {
        if (jTextField_namePlayer.getText().equals("")) {
            JOptionPane.showMessageDialog(JPanel_main, "Per començar a jugar s'ha d'introduir un nom!", "Error!", JOptionPane.ERROR_MESSAGE);
        } else if (Classificacio.existeixPresoner(jTextField_namePlayer.getText(), arxiu_classificacio)) {
            JOptionPane.showMessageDialog(JPanel_main, "El presoner "+jTextField_namePlayer.getText()+" ja existeix a la classificació!", "Error!", JOptionPane.ERROR_MESSAGE);
        } else {
            ini_game.setEnabled(false);
            jTextField_namePlayer.setEnabled(false);
            jLabel_punts_p2.setText(jTextField_namePlayer.getText() + ":");
            jButtonp2_betray.setEnabled(true);
            jButtonp2_cooperate.setEnabled(true);
        }
    }

    /**
     * Mètode que conté les accions si el jugador fa ús del botó Cooperate.
     */
    private void accionsCooperate() {
        Action cooperar = Action.cooperate;
        Action decision_op = p1.decision();
        if (decision_op.equals(Action.cooperate)) {

            jTextLabel_decisionOpp.setForeground(Color.green);
        } else {
            jTextLabel_decisionOpp.setForeground(Color.red);
        }
        jTextLabel_decisionOpp.setText(String.valueOf(decision_op));

        if (decision_op == Action.cooperate) {
            punts_p1 += cooperacio;
            punts_p2 += cooperacio;
            jLabel_puntsP1.setText(String.valueOf(punts_p1));
            jLabel_puntsP2.setText(String.valueOf(punts_p2));
        } else if (decision_op == Action.betray) {
            punts_p2 += traicio;
            jLabel_puntsP1.setText(String.valueOf(punts_p1));
            jLabel_puntsP2.setText(String.valueOf(punts_p2));
        }
        p1.setOpponentDecision(cooperar);
        decisions[0] = String.valueOf(iteracions);
        decisions[1] = String.valueOf(decision_op);
        decisions[2] = String.valueOf(cooperar);
        table_model.addRow(decisions);
        jTable_historial.changeSelection(jTable_historial.getRowCount() - 1, 0, false, false);
        iteracions--;
        jLabel_iteracions.setText(String.valueOf(iteracions));
        if (iteracions == 0) {
            finJoc();
        }
    }

    /**
     * Mètode que conté les accions si el jugador fa ús del botó Betray.
     */
    private void accionsBetray() {
        Action trair = Action.betray;
        Action decision_op = p1.decision();

        if (decision_op.equals(Action.cooperate)) {
            jTextLabel_decisionOpp.setForeground(Color.green);
        } else {
            jTextLabel_decisionOpp.setForeground(Color.red);
        }
        jTextLabel_decisionOpp.setText(String.valueOf(decision_op));

        if (decision_op == Action.cooperate) {
            punts_p1 += traicio;
            jLabel_puntsP1.setText(String.valueOf(punts_p1));
            jLabel_puntsP2.setText(String.valueOf(punts_p2));
        }
        p1.setOpponentDecision(trair);
        decisions[0] = String.valueOf(iteracions);
        decisions[1] = String.valueOf(decision_op);
        decisions[2] = String.valueOf(trair);
        table_model.addRow(decisions);
        jTable_historial.changeSelection(jTable_historial.getRowCount() - 1, 0, false, false);
        iteracions--;
        jLabel_iteracions.setText(String.valueOf(iteracions));
        if (iteracions == 0) {
            finJoc();
        }
    }

    /**
     * Obtenció de la imatge del presoner oponent.
     */
    private void getImagePresoners() {
        img_presoner_p2 = new ImageIcon(img_presoner_p2.getImage().getScaledInstance(jLabel_imgPrisoner_p2.getWidth(), jLabel_imgPrisoner_p2.getHeight(), Image.SCALE_DEFAULT));
        jLabel_imgPrisoner_p2.setIcon(img_presoner_p2);
    }

    /**
     * Mètode que conté les accions quan es finalitza la partida.
     */
    private void finJoc() {
        jButtonp2_cooperate.setEnabled(false);
        jButtonp2_betray.setEnabled(false);

        if (Classificacio.es_buit(arxiu_classificacio)) {
            Classificacio.nouPresoner(jTextField_namePlayer.getText(), punts_p1, arxiu_classificacio);
            Classificacio.obtenirPresoner(arxiu_classificacio);
            Classificacio.ranking(jTextField_namePlayer.getText());
        } else {
            Classificacio.obtenirPresoner(arxiu_classificacio);
            Classificacio.nouPresoner(jTextField_namePlayer.getText(), punts_p1, arxiu_classificacio);
            Classificacio.ranking(jTextField_namePlayer.getText());
        }
    }

    /**
     * Mètode que s'encarrega d'obtenir els paràmetres del joc. 
     * @param parametres Arxiu de paràmetres
     */
    private void obtenirParametres(String parametres) {
        try {
            FileInputStream file = new FileInputStream(parametres);
            BufferedReader in = new BufferedReader(new InputStreamReader(file));
            for (int i = 0; i < this.parametres.length; i++) {
                this.parametres[i] = Integer.parseInt(in.readLine());
            }
            this.iteracions = this.parametres[0];
            this.cooperacio = this.parametres[2];
            this.traicio = this.parametres[1];
        } catch (FileNotFoundException exFNF) {
            JOptionPane.showMessageDialog(JPanel_main, "No existeix arxiu de paràmetres!", "Error!", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        } catch (IOException ex) {
            ex.getMessage();
        }
    }

}
